pipeline{
    agent any
    environment {
        PATH = "$PATH:/usr/share/maven-3.6.3/bin"
    }
    stages{
       stage('GetCode'){
            steps{
                git 'https://github.com/anildv/sonar.git'
            }
         }        
       stage('Build'){
            steps{
                sh 'mvn clean package'
            }
         }
        stage('SonarQube analysis') {
//    def scannerHome = tool 'SonarScanner 4.0';
        steps{
        withSonarQubeEnv('sonarqube-9.5') { 
            withSonarQubeEnv(credentialsId: 'sonarqube-9.5') 

        sh "mvn sonar:sonar"
    }
        }
        }
       
    }
}
